#!/usr/bin/env python3

# Import the Halite SDK, which will let you interact with the game.
import hlt     #NPR
from hlt import constants   #NPR

import random   #NPR
import logging  #NPR

game = hlt.Game() # This game object contains the initial game state.
game.ready("PaulBot0002")   #PR- this command (<<) is us saying we are ready to play. above we can make decisions with given info(#players, etc)

while True: #while game is on
    
    game.update_frame()     #PR- command below updates the game state
    
    me = game.me    # Engine extracts player metadata and the updated map metadata here for convenience.
    game_map = game.game_map

    #PR-info now available:magnitude & loc of H in each coord, coord and mag-of-H of each ship, mag of stored H for each player
    # A command queue holds all the commands you will run this turn.
    command_queue = []

    ship_status = {}
  
    for ship in me.get_ships():
        # For each of your ships, move randomly if the ship is on a low halite location or the ship is full.
        #   Else, collect halite. #PR-just by staying still halite is collected.
        #PR-idea: if last ship moved N, move S, in order to avoid collisions(assuming the nearby ships are the ones that\
            #PR2 this is only sort of a good idea, no better than random (if #1is west,moves east, and #2 is east, told to move west.
            #PR3-this gives them a chance of collision
        #debug PR logging.info("Ship {} has {} halite.".format(ship.id, ship.halite_amount))
        if ship.id not in ship_status:
            ship_status[ship.id] = "exploring"
            
        if ship_status[ship.id] == "returning":
            
            if ship.position == me.shipyard.position:
                ship_status[ship.id] = "exploring"
        
        if ship.halite_amount >= constants.MAX_HALITE / 4:
            ship_status[ship.id] = "returning"

        if game_map[ship.position].halite_amount < constants.MAX_HALITE / 10 or ship.is_full:
            command_queue.append(
                ship.move(random.choice(["n", "s", "e", "w"])))
        else:
            move = game_map.naive_navigate(ship, me.shipyard.position)
            command_queue.append(ship.move(move))
        
#nulled        #else:
#nulled         #   command_queue.append(ship.stay_still())

    # If you're on the first turn and have enough halite, spawn a ship.
    # Don't spawn a ship if you currently have a ship at port, though. #PR - S can collide at P
    if game.turn_number <= 1 and me.halite_amount >= constants.SHIP_COST and not game_map[me.shipyard].is_occupied:
        command_queue.append(game.me.shipyard.spawn())
    #debug PR if me.halite_amount >= constant.SHIP_COST and not game_map[me.shipyard].is_occupied and not me.halite_amount <= 2000 :
    #    command_queue.append(game.me.shipyard.spawn())
    #PR if # ships is >8, stop building

    # Send your moves back to the game environment, ending this turn.
    game.end_turn(command_queue)

#When your ship collects halite on its turn, it will collect 25% of halite available in its location, rounded up
#You'll gain any halite cargo on that ship and the halite in the sea beneath the dropoff. 
